version: '3.9'
services:
  csharp-service:
    image: elainasuki/rc2025:csharp
    container_name: csharp-container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      # - ${XAUTHORITY}:/root/.Xauthority
      #可以在windows下使用WSL2的X11服务器但是需要在windows环境目录中添加WSL_X11_SOCKET环境变量
      - ${WSL_X11_SOCKET:-/tmp/.X11-unix}:/tmp/.X11-unix #如果没有设置WSL_X11_SOCKET则使用默认的/tmp/.X11-unix
      - ./..:/home/Elaina/csharp
    network_mode: host
    pid: "host"
    ipc: "host"
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina"
    # runtime: "nvidia"
    working_dir: "/home/Elaina/csharp"
    # profiles:
